version: 2.1

# reusable environment for all jobs
executors:
  node-executor:
    working_directory: ~/widgets
    docker:
      - image: cimg/node:20.13.1-browsers

# reusable command for all jobs
commands:
  checkout_from_workspace:
    description: 'To checkout and attach the workspace'
    steps:
      - checkout
      - attach_workspace:
          at: ~/widgets

# define jobs
jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/*/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - packages/*/node_modules

  linter:
    executor: node-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Linting
          command: yarn workspace @webex/widgets run test:eslint

  e2e_test:
    executor: node-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Test E2E
          command: yarn workspace @webex/widgets run test:e2e

  build:
    executor: node-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Build
          command: yarn workspace @webex/widgets run build && yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - packages/contact-center/station-login/dist
            - packages/contact-center/store/dist
            - packages/contact-center/user-state/dist
            - packages/@webex/widgets/dist

  docs:
    executor: node-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Build Demo Into Docs Folder
          command: yarn workspace @webex/widgets run demo:build
      - persist_to_workspace:
          root: .
          paths:
            - packages/@webex/widgets/docs

  release:
    executor: node-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Release
          command: yarn workspace @webex/widgets run release
  
  release_widgets:
    executor: node-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Release Widgets
          command: yarn run release:widgets

# execute the jobs in an orderly manner
workflows:
  setup_test_release:
    jobs:
      - install
      - linter:
          requires:
            - install
      - build:
          requires:
            - linter
          filters:
            branches:
              only: 
                - master
                - eft_pipeline
      - docs:
          requires:
            - linter
          filters:
            branches:
              only: 
                - master
      - release:
          requires:
            - build
            - docs
          filters:
            branches:
              only: master
      - release_widgets:
          requires:
            - build
          filters:
            branches:
              only: eft_pipeline
