version: 2.1

# reusable environment for all jobs
executors:
  node-executor:
    working_directory: ~/widgets
    docker:
      - image: cimg/node:20.13.1-browsers

# reusable command for all jobs
commands:
  checkout_from_workspace:
    description: 'To checkout and attach the workspace'
    steps:
      - checkout
      - attach_workspace:
          at: ~/widgets

# define jobs
jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: node_modules

  linter:
    executor: node-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Linting
          command: npm run test:eslint
  e2e_test:
    executor: node-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Test E2E
          command: npm run test:e2e

  build:
    executor: node-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: dist

  docs:
    executor: node-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Build Demo Into Docs Folder
          command: npm run demo:build
      - persist_to_workspace:
          root: .
          paths: docs

  release:
    executor: node-executor
    steps:
      - checkout_from_workspace
      - run:
          name: Release
          command: npm run release

# execute the jobs in a orderly manner
workflows:
  setup_test_release:
    jobs:
      - install
      - linter:
          requires:
            - install
      - build:
          requires:
            - linter
          filters:
            branches:
              only: master
      - docs:
          requires:
            - linter
          filters:
            branches:
              only: master
      - release:
          requires:
            - build
            - docs
          filters:
            branches:
              only: master
